import FieldAutocompleteComponent from './components/Autocomplete';
import FieldCheckboxComponent from './components/Checkbox';
import FieldColorComponent from './components/Color';
import FieldDateComponent from './components/Date';
import FieldHiddenComponent from './components/Hidden';
import FieldRadioComponent from './components/Radio';
import FieldSelectComponent from './components/Select';
import FieldSwitchComponent from './components/Switch';
import FieldTextComponent from './components/Text';
export * from './config';
export declare const FieldColor: typeof FieldColorComponent;
export declare const FieldText: typeof FieldTextComponent;
export declare const FieldSelect: typeof FieldSelectComponent;
export declare const FieldRadio: typeof FieldRadioComponent;
export declare const FieldCheckbox: typeof FieldCheckboxComponent;
export declare const FieldSwitch: typeof FieldSwitchComponent;
export declare const FieldDate: typeof FieldDateComponent;
export declare const FieldAutocomplete: typeof FieldAutocompleteComponent;
export declare const FieldHidden: typeof FieldHiddenComponent;
export declare const CustomMessage: any;
export declare const ValidationContext: any;
